# Generated by Django 4.0 on 2021-12-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Public Holiday ',
            },
        ),
        migrations.CreateModel(
            name='HolidayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=100)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.holiday')),
            ],
            options={
                'verbose_name_plural': 'Holiday Dates',
            },
        ),
    ]
