# Generated by Django 4.0 on 2021-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmaster', '0002_salaryyear_salaryperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hour_name', models.CharField(max_length=100)),
                ('normal_hour', models.CharField(max_length=2)),
                ('sun', models.CharField(max_length=2)),
                ('mon', models.CharField(max_length=2)),
                ('tue', models.CharField(max_length=2)),
                ('wed', models.CharField(max_length=2)),
                ('thu', models.CharField(max_length=2)),
                ('fri', models.CharField(max_length=2)),
                ('sat', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Working Hours',
            },
        ),
    ]
