# Generated by Django 4.0 on 2021-12-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_house_allowance_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='EmpName')),
                ('days', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Total Hours')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.attendance')),
                ('employee_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
        ),
    ]
