# Generated by Django 4.0 on 2022-01-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedetail',
            name='leaves',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Leaves'),
        ),
    ]
