# Generated by Django 4.0 on 2021-12-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmaster', '0003_workinghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_no', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=11)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pin_no', models.CharField(blank=True, max_length=11, null=True)),
                ('nssf_no', models.CharField(blank=True, max_length=11, null=True)),
                ('nhif_no', models.CharField(blank=True, max_length=11, null=True)),
                ('work_hours_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.workinghour')),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
